[IDS] Add support for slider captcha since enforced
xdlinux/libxduauth pull request #12
Opened 2024-03-05 04:23 UTC by Pairman

Add support for slider captcha for IDS session.

Dumped checking for whether captcha is needed since it's now enforced.

For slider captcha, only the background image is currently used in this script.

2024-03-05 04:27 UTC, Pairman commented
There's also comment blocks for usage because this is quite new.

2024-03-05 04:45 UTC, frankli0324 commented on libxduauth/sites/ids.py
> +                'rememberMe': True
这里是API接口变了吗？之前抓到的type是string

2024-03-05 04:45 UTC, frankli0324 commented on libxduauth/sites/ids.py
> +        move_len = input('滑块位移:')
这里的用户体验不知道能否好一点

2024-03-05 04:45 UTC, frankli0324 commented on libxduauth/sites/ids.py
> -            'https://ids.xidian.edu.cn/authserver/checkNeedCaptcha.htl',
这个要保留

2024-03-05 04:54 UTC, frankli0324 requested changes

2024-03-05 04:54 UTC, frankli0324 commented on libxduauth/sites/ids.py
> +                'rememberMe': True
requests在form里会把bool序列化为首字母大写的"True"，与实际不符，需要使用字符串形式的'true'

2024-03-06 01:24 UTC, Pairman commented on libxduauth/sites/ids.py
> +        move_len = input('滑块位移:')
dumb yet useful enough at this point. 
对于图形化界面来说，Image.open().show()以后用户可以自己打开图片编辑模式裁剪一下看看左边框位置。
对于cli来说，可以引入cv之类进行处理，但是从模块大小和风险方面来说就不太方便实现了

2024-03-06 07:25 UTC, frankli0324 approved these changes

2024-03-06 07:26 UTC, merged